import { img, PHOTOS } from "@/assets/images";

// Default inventory seed — loaded into ShoeContext when localStorage is empty (first visit).
// All entries are real inventory records fully compatible with the Shoe data model.

export const SEED_SHOES = [
  {
    id: "seed-1",
    brand: "Jordan Brand",
    name: "Air Jordan 1 Cactus Jack",
    price: 895,
    cost: 600,
    size: "10",
    condition: "New",
    status: "Available",
    category: "Sneakers",
    description: "Travis Scott x Air Jordan 1 Retro High OG. Reverse Nike Swoosh. DS with original box and all accessories.",
    image_url: img(PHOTOS.jordan1CactusJack),
    additional_images: [],
    created_date: "2026-03-15T10:00:00.000Z",
  },
  {
    id: "seed-2",
    brand: "Nike",
    name: "Air Force 1 '07 White",
    price: 120,
    cost: 90,
    size: "11",
    condition: "Like New",
    status: "Available",
    category: "Sneakers",
    description: "Classic AF1 Low in all-white leather. Worn once, clean soles, no creases.",
    image_url: img(PHOTOS.airForce1White),
    additional_images: [],
    created_date: "2026-03-16T10:00:00.000Z",
  },
  {
    id: "seed-3",
    brand: "Nike",
    name: "Air Max 90 White/Orange",
    price: 155,
    cost: 110,
    size: "9.5",
    condition: "New",
    status: "Available",
    category: "Sneakers",
    description: "Deadstock Air Max 90 in the White/Orange colorway. Full original box and laces.",
    image_url: img(PHOTOS.airMax90Orange),
    additional_images: [],
    created_date: "2026-03-17T10:00:00.000Z",
  },
  {
    id: "seed-4",
    brand: "Nike",
    name: "SB Blazer Mid '77",
    price: 100,
    cost: 70,
    size: "10.5",
    condition: "Gently Used",
    status: "Sold",
    category: "Sneakers",
    description: "Nike SB Blazer Mid in premium suede. Light wear, very clean, box included.",
    image_url: img(PHOTOS.sbBlazerMid),
    additional_images: [],
    created_date: "2026-03-18T10:00:00.000Z",
  },
  {
    id: "seed-5",
    brand: "Nike",
    name: "SB Blazer Low '77 Suede",
    price: 90,
    cost: 65,
    size: "9",
    condition: "New",
    status: "Sold",
    category: "Sneakers",
    description: "DS SB Blazer Low in earthy suede tones. Perfect for everyday wear.",
    image_url: img(PHOTOS.sbBlazerLow),
    additional_images: [],
    created_date: "2026-03-19T10:00:00.000Z",
  },
  {
    id: "seed-6",
    brand: "Jordan Brand",
    name: "Air Jordan 1 Low Red/White",
    price: 130,
    cost: 95,
    size: "11.5",
    condition: "Like New",
    status: "On Hold",
    hold_name: "Marcus T.",
    hold_until: "2026-04-10",
    category: "Sneakers",
    description: "AJ1 Low in classic Red/White. Worn a few times, soles clean, box included.",
    image_url: img(PHOTOS.jordan1LowRedWhite),
    additional_images: [],
    created_date: "2026-03-20T10:00:00.000Z",
  },
  {
    id: "seed-7",
    brand: "Nike",
    name: "Air Force 1 Shadow",
    price: 110,
    cost: 80,
    size: "10",
    condition: "New",
    status: "Available",
    category: "Sneakers",
    description: "AF1 Shadow with layered double Swoosh detail. Deadstock, all original packaging.",
    image_url: img(PHOTOS.airForce1Shadow),
    additional_images: [],
    created_date: "2026-03-21T10:00:00.000Z",
  },
  {
    id: "seed-8",
    brand: "Nike",
    name: "Air Force 1 Triple White",
    price: 95,
    cost: 70,
    size: "10",
    condition: "Like New",
    status: "Available",
    category: "Sneakers",
    description: "AF1 Low Triple White — the all-white staple. Very clean, minor wear on insoles only.",
    image_url: img(PHOTOS.airForce1TripleWht),
    additional_images: [],
    created_date: "2026-03-22T10:00:00.000Z",
  },
  {
    id: "seed-9",
    brand: "Nike",
    name: "Dunk Low Pine Green",
    price: 140,
    cost: 95,
    size: "6",
    condition: "New",
    status: "On Hold",
    hold_name: "Test Hold",
    hold_until: "2026-04-20",
    category: "Sneakers",
    description: "Pine Green Dunk Low, deadstock, original box included.",
    image_url: img(PHOTOS.airMax90Orange),
    additional_images: [],
    created_date: "2026-03-23T10:00:00.000Z",
  },
  {
    id: "seed-10",
    brand: "Adidas",
    name: "UltraBoost Triple Black",
    price: 160,
    cost: 100,
    size: "6.5",
    condition: "New",
    status: "Available",
    category: "Running",
    description: "Comfortable UltraBoost in triple black, deadstock.",
    image_url: img(PHOTOS.airForce1White),
    additional_images: [],
    created_date: "2026-03-24T10:00:00.000Z",
  },
  {
    id: "seed-11",
    brand: "New Balance",
    name: "550 White",
    price: 95,
    cost: 60,
    size: "7",
    condition: "Like New",
    status: "Sold",
    category: "Sneakers",
    description: "Classic NB 550 in white, gently used.",
    image_url: img(PHOTOS.jordan1LowRedWhite),
    additional_images: [],
    created_date: "2026-03-25T10:00:00.000Z",
  },
  {
    id: "seed-12",
    brand: "Puma",
    name: "RS-X Core",
    price: 85,
    cost: 50,
    size: "7.5",
    condition: "New",
    status: "On Hold",
    hold_name: "Hold Test 2",
    hold_until: "2026-04-22",
    category: "Lifestyle",
    description: "Bold RS-X colorway, DS, original box.",
    image_url: img(PHOTOS.airForce1Shadow),
    additional_images: [],
    created_date: "2026-03-26T10:00:00.000Z",
  },
  {
    id: "seed-13",
    brand: "Converse",
    name: "Chuck Taylor All Star",
    price: 60,
    cost: 30,
    size: "8.5",
    condition: "New",
    status: "Available",
    category: "Casual",
    description: "Classic Chuck Taylor in good condition.",
    image_url: img(PHOTOS.airForce1TripleWht),
    additional_images: [],
    created_date: "2026-03-27T10:00:00.000Z",
  },
  {
    id: "seed-14",
    brand: "Yeezy",
    name: "Boost 350 V2",
    price: 400,
    cost: 250,
    size: "12",
    condition: "New",
    status: "Sold",
    category: "Sneakers",
    description: "Yeezy Boost 350 V2, deadstock.",
    image_url: img(PHOTOS.jordan1CactusJack),
    additional_images: [],
    created_date: "2026-03-28T10:00:00.000Z",
  },
  {
    id: "seed-15",
    brand: "Reebok",
    name: "Club C 85",
    price: 70,
    cost: 40,
    size: "13",
    condition: "New",
    status: "Available",
    category: "Casual",
    description: "Reebok Club C in clean white leather.",
    image_url: img(PHOTOS.sbBlazerMid),
    additional_images: [],
    created_date: "2026-03-29T10:00:00.000Z",
  },
  {
    id: "seed-16",
    brand: "Vans",
    name: "Old Skool",
    price: 65,
    cost: 35,
    size: "4.5",
    condition: "New",
    status: "Available",
    category: "Skate",
    description: "Classic Vans Old Skool, new.",
    image_url: img(PHOTOS.sbBlazerLow),
    additional_images: [],
    created_date: "2026-03-30T10:00:00.000Z",
  },
];
