import { img, PHOTOS } from "@/assets/images";

// Default inventory seed — loaded into ShoeContext when localStorage is empty (first visit).
// All entries are real inventory records fully compatible with the Shoe data model.

export const SEED_SHOES = [
  {
    id: "seed-1",
    brand: "Jordan Brand",
    name: "Air Jordan 1 Cactus Jack",
    price: 895,
    cost: 600,
    size: "10",
    condition: "New",
    status: "Available",
    category: "Sneakers",
    description: "Travis Scott x Air Jordan 1 Retro High OG. Reverse Nike Swoosh. DS with original box and all accessories.",
    image_url: img(PHOTOS.jordan1CactusJack),
    additional_images: [],
    created_date: "2026-03-15T10:00:00.000Z",
  },
  {
    id: "seed-2",
    brand: "Nike",
    name: "Air Force 1 '07 White",
    price: 120,
    cost: 90,
    size: "11",
    condition: "Like New",
    status: "Available",
    category: "Sneakers",
    description: "Classic AF1 Low in all-white leather. Worn once, clean soles, no creases.",
    image_url: img(PHOTOS.airForce1White),
    additional_images: [],
    created_date: "2026-03-16T10:00:00.000Z",
  },
  {
    id: "seed-3",
    brand: "Nike",
    name: "Air Max 90 White/Orange",
    price: 155,
    cost: 110,
    size: "9.5",
    condition: "New",
    status: "Available",
    category: "Sneakers",
    description: "Deadstock Air Max 90 in the White/Orange colorway. Full original box and laces.",
    image_url: img(PHOTOS.airMax90Orange),
    additional_images: [],
    created_date: "2026-03-17T10:00:00.000Z",
  },
  {
    id: "seed-4",
    brand: "Nike",
    name: "SB Blazer Mid '77",
    price: 100,
    cost: 70,
    size: "10.5",
    condition: "Gently Used",
    status: "Sold",
    category: "Sneakers",
    description: "Nike SB Blazer Mid in premium suede. Light wear, very clean, box included.",
    image_url: img(PHOTOS.sbBlazerMid),
    additional_images: [],
    created_date: "2026-03-18T10:00:00.000Z",
  },
  {
    id: "seed-5",
    brand: "Nike",
    name: "SB Blazer Low '77 Suede",
    price: 90,
    cost: 65,
    size: "9",
    condition: "New",
    status: "Sold",
    category: "Sneakers",
    description: "DS SB Blazer Low in earthy suede tones. Perfect for everyday wear.",
    image_url: img(PHOTOS.sbBlazerLow),
    additional_images: [],
    created_date: "2026-03-19T10:00:00.000Z",
  },
  {
    id: "seed-6",
    brand: "Jordan Brand",
    name: "Air Jordan 1 Low Red/White",
    price: 130,
    cost: 95,
    size: "11.5",
    condition: "Like New",
    status: "On Hold",
    hold_name: "Marcus T.",
    hold_until: "2026-04-10",
    category: "Sneakers",
    description: "AJ1 Low in classic Red/White. Worn a few times, soles clean, box included.",
    image_url: img(PHOTOS.jordan1LowRedWhite),
    additional_images: [],
    created_date: "2026-03-20T10:00:00.000Z",
  },
  {
    id: "seed-7",
    brand: "Nike",
    name: "Air Force 1 Shadow",
    price: 110,
    cost: 80,
    size: "10",
    condition: "New",
    status: "Available",
    category: "Sneakers",
    description: "AF1 Shadow with layered double Swoosh detail. Deadstock, all original packaging.",
    image_url: img(PHOTOS.airForce1Shadow),
    additional_images: [],
    created_date: "2026-03-21T10:00:00.000Z",
  },
  {
    id: "seed-8",
    brand: "Nike",
    name: "Air Force 1 Triple White",
    price: 95,
    cost: 70,
    size: "10",
    condition: "Like New",
    status: "Available",
    category: "Sneakers",
    description: "AF1 Low Triple White — the all-white staple. Very clean, minor wear on insoles only.",
    image_url: img(PHOTOS.airForce1TripleWht),
    additional_images: [],
    created_date: "2026-03-22T10:00:00.000Z",
  },
];
